# Generated by Django 5.0.6 on 2024-06-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20)),
                ('trade_code', models.CharField(max_length=20)),
                ('high', models.CharField(max_length=20)),
                ('low', models.CharField(max_length=20)),
                ('open', models.CharField(max_length=20)),
                ('close', models.CharField(max_length=20)),
                ('volume', models.CharField(max_length=20)),
            ],
        ),
    ]
